public class GameEnums
{
    public enum AnimalCharcter
    {

        Alligator,
        Bear,
        Cat,
        Dog,
        Elephant,
        Flamingo,
        Gorilla,
        Hippo,
        Iguana,
        Jellyfish,
        Koala,
        Lion,
        Monkey,
        Newt,
        Octopus,
        Panda,
        Quail,
        Raccoon,
        Snail,
        Turtle,
        Uakari,
        Vulture,
        Walrus,
        Xenarthra,
        Yak,
        Zebra
    }

    public enum StoryObjects
    {
        None,
        Book,
        Laptop,
        Mirror,
        Mouse,
        Fan,
        Bottle,
        Bag,
        Glasses,
        Calculator,
        Charger,
        Spoon,
        ToyCar,
        Slippers,
        Pajamas,
        Shorts,
        Flipflops,
        Pen,
        Phone,
        Umbrella,
        Wrench,
        Hat,
        ScrewDriver,
        Chapstick,
        SunGlasses,
        Flowers,
        Chocolate,
        NightLight,
        Jacket,
        Binoculars,
        LunchBox,
        RemoteControle,
        Medicine,
        Map,
        Telescope,
        Markers,
        Tape,
        Cake,
        RainCoat,
        Watch,
        HeadPhones,



    }
}
